#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure misc/rlwrap
  "$shome/bin/lein" >/dev/null || true
}

bootstrap
