#!/usr/bin/env bash

function _leiningen_profile {
  local shome="${_leiningen_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"
  
  export LEIN_HOME="$shome"
  export LEIN_VERSION='2.7.1'
}

_leiningen_profile
