#!/usr/bin/env bash

function profile {
  local shome="${_leiningen_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"
  
  export LEIN_HOME="$shome"
}

profile
