#!/usr/bin/env bash

function bootstrap {
  local shome="${_leiningen_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -f "$shome/self-installs/leiningen-2.6.1-standalone.jar" ]]; then
    return 1
  fi

  return 0
}

bootstrap
