#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_lein="$(lein --version 2>/dev/null | awk '{print $2}' || true)"
  jq -n --arg lein "$ver_lein" '{lein: $lein}'
}

version "$@"
