#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_lein="$(lein --version 2>&- | awk '{print $2}' || true)"
  jq -n --arg lein "$ver_lein" '{leiningen: $lein}'
}

version "$@"
